[package]
name = "seaography"
version = "0.1.0"
edition = "2021"
authors = ["Panagiotis Karatakis <panagiotiskaratakis@gmail.com>"]

[dependencies]
seaography_derive = { path = "./derive" }
async-graphql = { version = "4.0.12", default-features = false }
sea-orm = { version = "0.9.2", default-features = false }

[workspace]
members = [
    ".",
    "cli",
    "derive",
    "discoverer",
    "generator",
]

[features]
default = []
with-chrono = ["sea-orm/with-chrono", "async-graphql/chrono"]
with-decimal = ["sea-orm/with-rust_decimal", "async-graphql/decimal"]
with-uuid = ["sea-orm/with-uuid"]