[workspace]
members = [
    ".",
    "cli",
    "derive",
    "discoverer",
    "generator",
]

[package]
name = "seaography"
version = "0.1.0"
edition = "2021"
rust-version = "1.60"
authors = ["Panagiotis Karatakis <panagiotiskaratakis@gmail.com>"]
description = "🧭 A GraphQL framework and code generator for SeaORM"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/seaography"
repository = "https://github.com/SeaQL/seaography"
keywords = ["async", "graphql", "mysql", "postgres", "sqlite"]
categories = ["database"]

[dependencies]
async-graphql = { version = "4.0.12", default-features = false }
seaography-derive = { version = "^0.1", path = "./derive" }
sea-orm = { version = "^0.9", default-features = false }

[features]
default = []
with-chrono = ["sea-orm/with-chrono", "async-graphql/chrono"]
with-decimal = ["sea-orm/with-rust_decimal", "async-graphql/decimal"]
with-uuid = ["sea-orm/with-uuid"]