[package]
name = "seaography-cli"
version = "0.1.0"
edition = "2021"
authors = ["Panagiotis Karatakis <panagiotiskaratakis@gmail.com>"]

[dependencies]
seaography-generator = { path = "../generator" }
clap = { version = "3.2.20", features = ["derive"] }
async-std = { version = "1.12.0", features = [ "attributes", "tokio1" ] }
